name: Build, Unit + Selenium Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - uses: actions/checkout@v4

      # 2. Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build project and run JUnit + Selenium tests
      - name: Build with Maven and run unit + selenium tests
        run: mvn -f ./demo/pom.xml clean test
